export {default as Welcome } from './welcome/index'
export {default as Home} from './home/index'
export {default as Menu} from './hamburger-menu/index'
export {default as ProductList} from './product-list/index'
export {default as Cart} from './cart/index'
export {default as Orders} from './orders/index'
export {default as Auth} from './auth/index'
export {default as Product} from './product/index'